const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s); const content=$('#content'), title=$('#pageTitle');
const api=async(url,opt={})=>{const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let j={};try{j=await r.json()}catch{}if(r.status===401){showLogin();throw Error('Unauthorized')}if(!r.ok)throw Error(j.error||'Request failed');return j};
function showLogin(){ $('#app').hidden=true; $('#login').style.display='grid'; }
async function boot(){try{const me=await api('/api/auth/me');$('#login').style.display='none';$('#app').hidden=false;render('dashboard');}catch{showLogin()}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});boot()}catch(err){$('#loginError').textContent=err.message}});
$('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});showLogin()};
$('#theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('heego_admin_theme',document.body.classList.contains('dark')?'dark':'light')}; if(localStorage.getItem('heego_admin_theme')==='dark')document.body.classList.add('dark');
$$('.nav').forEach(b=>b.onclick=()=>{ $$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.page)});
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(m){const t=$('.toast')||Object.assign(document.body.appendChild(document.createElement('div')),{className:'toast'});t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',1800)}
async function render(page){title.textContent=({dashboard:'Dashboard',website:'Website Settings',services:'Services',portfolio:'Portfolio',packages:'Packages',messages:'Messages'})[page]; if(page==='dashboard')return dashboard(); if(page==='website')return website(); if(page==='services')return list('services'); if(page==='portfolio')return list('portfolio'); if(page==='packages')return list('packages'); if(page==='messages')return messages();}
async function dashboard(){const d=await api('/api/admin/dashboard');content.innerHTML=`<div class="grid">${[['Services',d.services],['Portfolio',d.portfolio],['Packages',d.packages],['Messages',d.messages]].map(x=>`<div class="card"><div class="muted">${x[0]}</div><div class="stat">${x[1]}</div></div>`).join('')}</div><div class="section-card"><h2>Quick Actions</h2><div class="actions"><button class="btn primary" onclick="render('services')">Manage Services</button><button class="btn primary" onclick="render('portfolio')">Manage Portfolio</button><button class="btn primary" onclick="render('packages')">Manage Packages</button></div></div>`}
async function website(){const d=await api('/api/public');const s=d.settings;content.innerHTML=`<div class="section-card"><h2>Homepage & Contact</h2><div class="form-grid"><div class="field full"><label>Hero Title</label><input id="hero_title" value="${esc(s.hero_title)}"></div><div class="field full"><label>Hero Description</label><textarea id="hero_lead">${esc(s.hero_lead)}</textarea></div><div class="field"><label>WhatsApp / Phone</label><input id="whatsapp" value="${esc(s.whatsapp)}"></div><div class="field"><label>Email</label><input id="email2" value="${esc(s.email)}"></div><div class="field full"><label>Behance URL</label><input id="behance" value="${esc(s.behance)}"></div></div><div class="actions"><button class="btn primary" onclick="saveSettings()">Save Changes</button></div></div>`}
async function saveSettings(){await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({hero_title:hero_title.value,hero_lead:hero_lead.value,whatsapp:whatsapp.value,email:email2.value,behance:behance.value})});toast('Saved');}
const configs={services:{title:'Services',fields:[['name','Service Name'],['description','Description']]},portfolio:{title:'Portfolio',fields:[['name','Project Name'],['category','Category'],['image','Image URL'],['link','Project URL']]},packages:{title:'Packages',fields:[['name','Package Name'],['tier','Tier'],['price','Price'],['items','Items (one per line)']]}};
async function list(type){const c=configs[type],rows=await api('/api/admin/'+type);content.innerHTML=`<div class="section-card"><h2>Add ${c.title.slice(0,-1)||c.title}</h2><form id="crudForm" class="form-grid">${c.fields.map(f=>`<div class="field ${f[0]==='description'||f[0]==='image'||f[0]==='link'||f[0]==='items'?'full':''}"><label>${f[1]}</label>${f[0]==='description'||f[0]==='items'?`<textarea name="${f[0]}"></textarea>`:`<input name="${f[0]}" ${f[0]==='image'?'placeholder="https://..."':''}>`}</div>`).join('')}<div class="actions full"><button class="btn primary">Add ${c.title.slice(0,-1)}</button></div></form></div><div class="section-card"><h2>Current ${c.title}</h2><div class="admin-list">${rows.map(x=>card(type,x)).join('')||'<p class="muted">Nothing added yet.</p>'}</div></div>`;$('#crudForm').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));if(type==='packages')b.items=b.items.split('\n').map(x=>x.trim()).filter(Boolean);await api('/api/admin/'+type,{method:'POST',body:JSON.stringify(b)});toast('Added successfully');render(type)};}
function card(type,x){if(type==='services')return `<div class="item-row"><div><b>${esc(x.name)}</b><p>${esc(x.description)}</p></div><button class="btn danger" onclick="del('${type}',${x.id})">Delete</button></div>`;if(type==='portfolio')return `<div class="item-row"><div class="item-media"><img src="${esc(x.image)}"><div><b>${esc(x.name)}</b><p>${esc(x.category)}</p></div></div><button class="btn danger" onclick="del('${type}',${x.id})">Delete</button></div>`;return `<div class="item-row"><div><b>${esc(x.name)} — ${esc(x.price)}</b><p>${esc(x.tier)} · ${(x.items||[]).join(' • ')}</p></div><button class="btn danger" onclick="del('${type}',${x.id})">Delete</button></div>`}
async function del(type,id){if(!confirm('Delete this item?'))return;await api('/api/admin/'+type+'/'+id,{method:'DELETE'});render(type)}
async function messages(){const rows=await api('/api/admin/messages');content.innerHTML=`<div class="section-card"><h2>Contact Messages</h2>${rows.map(x=>`<div class="item-row"><div><b>${esc(x.name)} — ${esc(x.email)}</b><p>${esc(x.phone)} · ${new Date(x.created_at).toLocaleString()}</p><p>${esc(x.message)}</p></div><button class="btn danger" onclick="delMessage(${x.id})">Delete</button></div>`).join('')||'<p class="muted">No messages yet.</p>'}</div>`}
async function delMessage(id){if(!confirm('Delete message?'))return;await api('/api/admin/messages/'+id,{method:'DELETE'});messages()}
boot();
