const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{DatabaseSync}=require('node:sqlite'),querystring=require('node:querystring');
const ROOT=__dirname,PORT=Number(process.env.PORT||3000);fs.mkdirSync(path.join(ROOT,'data'),{recursive:true});
const db=new DatabaseSync(path.join(ROOT,'data','heego.db'));
db.exec(`PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY,email TEXT UNIQUE,password_hash TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,admin_id INTEGER NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),hero_title TEXT,hero_lead TEXT,whatsapp TEXT,email TEXT,behance TEXT);
CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT NOT NULL,sort_order INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS portfolio(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category TEXT,image TEXT,link TEXT,sort_order INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS packages(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,tier TEXT,price TEXT,items TEXT,sort_order INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,email TEXT,phone TEXT,message TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
function hashPassword(p){const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(p,salt,64).toString('hex');return `${salt}:${hash}`}
function verifyPassword(p,stored){const [salt,hash]=String(stored).split(':');if(!salt||!hash)return false;const actual=crypto.scryptSync(p,salt,64);return crypto.timingSafeEqual(actual,Buffer.from(hash,'hex'))}
if(!db.prepare('SELECT 1 FROM admins LIMIT 1').get()){const email=process.env.ADMIN_EMAIL||'admin@heegocreative.com',pass=process.env.ADMIN_PASSWORD||'ChangeMe123!';db.prepare('INSERT INTO admins(email,password_hash) VALUES(?,?)').run(email,hashPassword(pass));}
if(!db.prepare('SELECT 1 FROM settings WHERE id=1').get())db.prepare('INSERT INTO settings(id,hero_title,hero_lead,whatsapp,email,behance) VALUES(1,?,?,?,?,?)').run('We Build Powerful Brands.','We build powerful brands through strategy, creativity, and meaningful visual communication.','+252 61 947 8973','heegocreative@gmail.com','https://www.behance.net/heegocreative');
if(!db.prepare('SELECT 1 FROM services LIMIT 1').get()){const q=db.prepare('INSERT INTO services(name,description,sort_order) VALUES(?,?,?)');[['Brand Strategy','Strategic foundations that give brands clarity, direction, and a competitive identity.'],['Logo & Brand Identity','Distinctive logos and complete visual identity systems that make brands recognizable.'],['Graphic Design','Professional visual communication for social media, campaigns and marketing materials.'],['Digital Marketing','Creative campaigns, content and strategic communication that strengthen digital presence.']].forEach((x,i)=>q.run(x[0],x[1],i));}
if(!db.prepare('SELECT 1 FROM portfolio LIMIT 1').get()){const q=db.prepare('INSERT INTO portfolio(name,category,image,link,sort_order) VALUES(?,?,?,?,?)');[['BRAND IDENTITY COMPLETED','Branding','https://mir-s3-cdn-cf.behance.net/projects/404/bbf7f4249376765.6a0605f88da6a.png','https://www.behance.net/gallery/249376765/BRAND-IDENTITY-COMPLETED'],['Annual Da’wah Conference','Event Branding','https://mir-s3-cdn-cf.behance.net/projects/404/2d012f248309657.69ef02a933bd5.png','https://www.behance.net/gallery/248309657/Annual-Dawah-Conference'],['Samaad TV','Logo & Visual Identity','https://mir-s3-cdn-cf.behance.net/projects/404/94ae9f248309105.69ef00cce88ed.png','https://www.behance.net/gallery/248309105/logo-ga-Samaad-TV'],['Galkacyo Peace Week','Event Branding','https://mir-s3-cdn-cf.behance.net/projects/404/3f0002248308891.69eeff27b6cb9.png','https://www.behance.net/gallery/248308891/Event-Branding-Galkacyo-peace-weak']].forEach((x,i)=>q.run(...x,i));}
if(!db.prepare('SELECT 1 FROM packages LIMIT 1').get()){const q=db.prepare('INSERT INTO packages(name,tier,price,items,sort_order) VALUES(?,?,?,?,?)');[['Kaabe Package','Starter','$199',['8 posters','2 videos','Cover page','Page management']],['Kulmiye Package','Growth','$499',['12 posters','4 videos','Video animation','Cover page','Page management']],['Kobac Package','Scale','$599',['20 posters','5 videos','2 video animations','2 cover pages','Page management','Media consultant']]].forEach((x,i)=>q.run(x[0],x[1],x[2],JSON.stringify(x[3]),i));}
function send(res,status,data,type='json'){const body=type==='json'?JSON.stringify(data):data;res.writeHead(status,{'Content-Type':type==='json'?'application/json':'text/html; charset=utf-8','Content-Length':Buffer.byteLength(body)});res.end(body)}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
function authed(req){const t=cookies(req).heego_token;if(!t)return false;const s=db.prepare('SELECT * FROM sessions WHERE token=? AND expires_at>?').get(t,Date.now());return !!s}
async function body(req){let b='';for await(const c of req)b+=c;if(!b)return{};if((req.headers['content-type']||'').includes('application/json'))return JSON.parse(b);return querystring.parse(b)}
function json404(res){send(res,404,{error:'Not found'})}
function cleanPublic(){return{settings:db.prepare('SELECT * FROM settings WHERE id=1').get(),services:db.prepare('SELECT * FROM services ORDER BY sort_order,id').all(),portfolio:db.prepare('SELECT * FROM portfolio ORDER BY sort_order,id').all(),packages:db.prepare('SELECT * FROM packages ORDER BY sort_order,id').all().map(x=>({...x,items:JSON.parse(x.items||'[]')}))}}
function requireAuth(res,req){if(!authed(req)){send(res,401,{error:'Unauthorized'});return false}return true}
async function api(req,res,url){const p=url.pathname;
if(req.method==='POST'&&p==='/api/auth/login'){const b=await body(req),a=db.prepare('SELECT * FROM admins WHERE email=?').get(String(b.email||''));if(!a||!verifyPassword(String(b.password||''),a.password_hash))return send(res,401,{error:'Invalid email or password'});const token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions(token,admin_id,expires_at) VALUES(?,?,?)').run(token,a.id,Date.now()+8*60*60*1000);res.setHeader('Set-Cookie',`heego_token=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800`);return send(res,200,{ok:true,email:a.email});}
if(req.method==='POST'&&p==='/api/auth/logout'){const t=cookies(req).heego_token;if(t)db.prepare('DELETE FROM sessions WHERE token=?').run(t);res.setHeader('Set-Cookie','heego_token=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return send(res,200,{ok:true});}
if(req.method==='GET'&&p==='/api/auth/me'){if(!requireAuth(res,req))return;return send(res,200,{ok:true});}
if(req.method==='GET'&&p==='/api/public')return send(res,200,cleanPublic());
if(req.method==='POST'&&p==='/api/contact'){const b=await body(req);if(!b.name||!b.email||!b.message)return send(res,400,{error:'Name, email and message are required'});db.prepare('INSERT INTO messages(name,email,phone,message) VALUES(?,?,?,?)').run(b.name,b.email,b.phone||'',b.message);return send(res,200,{ok:true});}
if(!p.startsWith('/api/admin/'))return json404(res);if(!requireAuth(res,req))return;
if(req.method==='GET'&&p==='/api/admin/dashboard')return send(res,200,{services:db.prepare('SELECT COUNT(*) c FROM services').get().c,portfolio:db.prepare('SELECT COUNT(*) c FROM portfolio').get().c,packages:db.prepare('SELECT COUNT(*) c FROM packages').get().c,messages:db.prepare('SELECT COUNT(*) c FROM messages').get().c});
if(req.method==='GET'&&p==='/api/admin/messages')return send(res,200,db.prepare('SELECT * FROM messages ORDER BY id DESC').all());
if(req.method==='DELETE'&&p.startsWith('/api/admin/messages/')){db.prepare('DELETE FROM messages WHERE id=?').run(Number(p.split('/').pop()));return send(res,200,{ok:true});}
if(req.method==='PUT'&&p==='/api/admin/settings'){const b=await body(req);db.prepare('UPDATE settings SET hero_title=?,hero_lead=?,whatsapp=?,email=?,behance=? WHERE id=1').run(b.hero_title,b.hero_lead,b.whatsapp,b.email,b.behance);return send(res,200,{ok:true});}
const m=p.match(/^\/api\/admin\/(services|portfolio|packages)(?:\/(\d+))?$/);if(m){const table=m[1],id=m[2]?Number(m[2]):null;const fields={services:['name','description'],portfolio:['name','category','image','link'],packages:['name','tier','price','items']}[table];if(req.method==='GET'){const rows=db.prepare(`SELECT * FROM ${table} ORDER BY sort_order,id`).all().map(x=>table==='packages'?({...x,items:JSON.parse(x.items||'[]')}):x);return send(res,200,rows)}if(req.method==='POST'){const b=await body(req),vals=fields.map(f=>f==='items'?JSON.stringify(b[f]||[]):b[f]);db.prepare(`INSERT INTO ${table} (${fields.join(',')},sort_order) VALUES (${fields.map(()=>'?').join(',')},?)`).run(...vals,Number(b.sort_order||0));return send(res,201,{ok:true})}if(req.method==='PUT'&&id){const b=await body(req),vals=fields.map(f=>f==='items'?JSON.stringify(b[f]||[]):b[f]);db.prepare(`UPDATE ${table} SET ${fields.map(f=>f+'=?').join(',')},sort_order=? WHERE id=?`).run(...vals,Number(b.sort_order||0),id);return send(res,200,{ok:true})}if(req.method==='DELETE'&&id){db.prepare(`DELETE FROM ${table} WHERE id=?`).run(id);return send(res,200,{ok:true})}}
return json404(res)}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.webp':'image/webp'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return await api(req,res,url);let file=path.normalize(path.join(ROOT,url.pathname==='/'?'index.html':url.pathname));if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return json404(res);const data=fs.readFileSync(file);res.writeHead(200,{'Content-Type':mime[path.extname(file).toLowerCase()]||'application/octet-stream','Content-Length':data.length});res.end(data);}catch(e){console.error(e);send(res,500,{error:'Server error'})}});
server.listen(PORT,()=>console.log(`Heego Creative CMS: http://localhost:${PORT}`));
